SDKを一部更新しました
soracom/soracom-sdk-go pull request #13
Opened 2019-12-06 13:51 UTC by uzuna

## 内容
- go modules対応しました
- APIに対して不足しているメソッドをいくつか実装しました
- `CreateEventHandlerOptions` を組み立てやすくする関数を追加しました
- GitHub actionsでテストが動くようにしました

## 背景

実際使用するにあたり必要なREST APIをたたく実装ない、あるいは使うのにドキュメントを精読しなければリクエストボディが組み立てられず使いづらい点があったため、使いやすくなるように修正を加えました。

修正にあたり正しく動作していること、APIとの実装に差がないことが明示できるようにGitHub Actionsで外部APIをたたくTestが動くように設定を追加しました。

2020-04-01 16:00 UTC, moznion requested changes
反応が遅くなり大変申し訳ございません．pull-requestをお送りいただきありがとうございます！

レビューコメントでは網羅的に示していないのですが，golintが出力している警告についても全般的にご対応いただければ幸いです。
どうぞよろしくお願いいたします。

@bearmini なにか他にレビュー事項等あればfollow upいただければと思います．

2020-04-01 16:00 UTC, moznion commented on .github/workflows/go.yml
> +        if [ -f Gopkg.toml ]; then
本pull-requestでは go mod に対応していただいたかと思うのですが，`Gopkg.toml` は dep が利用するファイルのようにお見受けします．こちらは必要でしょうか？

2020-04-01 16:00 UTC, moznion commented on event.go
> +	IMMEDIATELY             = "IMMEDIATELY"
golintによる命名規約に対する警告が出ておりますのでご対応いただければと思います．

```
event.go:17:2: don't use ALL_CAPS in Go names; use CamelCase
```

2020-04-01 16:00 UTC, moznion commented on sdk_test.go
> +    "imsi": "000050910800000",
[nit] IMSIを構成する先頭3文字のコード (Mobile Country Code: MCC) において `000` は許可されておらず，テスト用途では `001` の利用を指示されております．本テストケースでもそれに則っていただけるとベターかと存じます．

2020-04-01 16:00 UTC, moznion commented on event.go
> +type EventDateTimeConst string
以降の同様の内容のコメントについては省きますが，golint による以下のような警告が出ておりますので，godocの追加についてご対応いただければと存じます．

```
event.go:9:6: exported type EventDateTimeConst should have comment or be unexported
```

2020-04-01 16:00 UTC, moznion commented on Makefile
> +	# test api client (ignore metadata client)
metadata clientのテストを省いている理由をお教えいただけますでしょうか

2020-04-01 16:00 UTC, moznion commented on Makefile
> +	go vet ./...
元コードにはなく，恐縮なのですが `golint` のチェックもこちらに含めていただくこと出来ますでしょうか．

2020-04-03 00:12 UTC, bearmini commented on Makefile
> +	# test api client (ignore metadata client)
@moznion 補足しますと実際の SIM がないと Metadata を取得できないため、Metadata Client のテストは CI 環境では実行しづらいのでここで省くのは仕方ないかなという気もします。

2020-04-03 02:30 UTC, moznion commented on Makefile
> +	# test api client (ignore metadata client)
補足ありがとうございます．理解しました．
とすると，この方法だと意図しないテストまでskipしてしまいそうなのでむしろテストケース側でケアすべきかなと思いました．これはまた別のpull-requestで行いたいと思います．

2020-04-03 02:46 UTC, moznion commented on Makefile
> +	# test api client (ignore metadata client)
#15 こちらで対応してみましたがいかがでしょうか

2020-04-03 05:08 UTC, bearmini commented on Makefile
> +	# test api client (ignore metadata client)
環境変数でテストする／しないを切り替えられる方法は汎用的で良いですね。
#15 を master にマージしました。
@uzuna こちらを使うようにしていただくと良いかもしれません。

2020-04-05 12:51 UTC, uzuna commented on .github/workflows/go.yml
> +        if [ -f Gopkg.toml ]; then
github actionのテンプレートからコピーしたため `Gopkg.toml` が残っていました。
語してこの通り不要なので削除しました。

2020-04-05 12:51 UTC, uzuna commented on event.go
> +	IMMEDIATELY             = "IMMEDIATELY"
CamelCaseに修正しました

2020-04-05 12:53 UTC, uzuna commented on event.go
> +type EventDateTimeConst string
当方で追加した構造体や定数に対してコメントの追加を行いました

2020-04-05 12:54 UTC, uzuna commented on Makefile
> +	go vet ./...
`make lint` を追加をしました

2020-04-05 13:02 UTC, uzuna commented on .github/workflows/go.yml
> +    - name: Lint
`go install`してもgolintにpathが通らなかったため[github actionsのissue](https://github.com/actions/setup-go/issues/14)を参考に追加しました。
github actionでの実現方法は他にいくつかありそうでしたが本PRの目的からずれるため依存が一番少ないと思われる方法をとりました。

2020-04-08 01:29 UTC, moznion commented on .github/workflows/go.yml
> +        if [ -f Gopkg.toml ]; then
ご対応ありがとうございます！

2020-04-08 01:33 UTC, moznion commented on Makefile
> +	go vet ./...
ご対応誠にありがとうございます，大変助かりました！

2020-04-08 01:33 UTC, moznion commented on .github/workflows/go.yml
> +    - name: Lint
ありがとうございます，こちらで良いかと存じます

2020-04-08 01:37 UTC, moznion approved these changes
ご対応くださいまして誠にありがとうございました！
残っているgolintのエラーに関しましては既存のコードの問題かと存じますので，別のp-rにて対応したいと思います．

2020-04-08 03:45 UTC, bearmini approved these changes
ご対応ありがとうございました！

2020-04-08 04:03 UTC, merged